"""token_confirmacao_remove_patient_push

Revision ID: 19620111776d
Revises: 5b6fca99392a
Create Date: 2026-02-26 19:12:04.640709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19620111776d'
down_revision: Union[str, Sequence[str], None] = '5b6fca99392a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('dispositivo_push_token')

    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_confirmacao', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_sessoes_token_confirmacao'), ['token_confirmacao'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessoes_token_confirmacao'))
        batch_op.drop_column('token_confirmacao')

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispositivo_push_token', sa.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
