"""Add onboarding fields

Revision ID: 2ec08493194d
Revises: 62209d02d22f
Create Date: 2026-02-28 17:29:59.080265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec08493194d'
down_revision: Union[str, Sequence[str], None] = '62209d02d22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_concluido', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('crp', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('duracao_sessao_padrao_minutos', sa.Integer(), server_default='50', nullable=False))
        batch_op.add_column(sa.Column('intervalo_sessao_padrao_minutos', sa.Integer(), server_default='10', nullable=False))
        batch_op.add_column(sa.Column('dias_atendimento', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('modelo_cobranca_padrao', sa.String(length=50), server_default='por_sessao', nullable=False))
        batch_op.add_column(sa.Column('valor_sessao_padrao', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('chave_pix', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('enviar_lembretes_automaticos', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('antecedencia_lembrete_horas', sa.Integer(), server_default='24', nullable=False))
        batch_op.add_column(sa.Column('cobrar_faltas_nao_avisadas', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessoes_data_hora_inicio'))
        batch_op.drop_index(batch_op.f('ix_sessoes_paciente_data_inicio'))

    with op.batch_alter_table('tarefas_paciente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarefas_paciente_data_vencimento'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefas_paciente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarefas_paciente_data_vencimento'), ['paciente_id', 'data_vencimento'], unique=False)

    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessoes_paciente_data_inicio'), ['paciente_id', 'data_hora_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessoes_data_hora_inicio'), ['data_hora_inicio'], unique=False)

    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.drop_column('cobrar_faltas_nao_avisadas')
        batch_op.drop_column('antecedencia_lembrete_horas')
        batch_op.drop_column('enviar_lembretes_automaticos')
        batch_op.drop_column('chave_pix')
        batch_op.drop_column('valor_sessao_padrao')
        batch_op.drop_column('modelo_cobranca_padrao')
        batch_op.drop_column('dias_atendimento')
        batch_op.drop_column('intervalo_sessao_padrao_minutos')
        batch_op.drop_column('duracao_sessao_padrao_minutos')
        batch_op.drop_column('crp')
        batch_op.drop_column('onboarding_concluido')

    # ### end Alembic commands ###
