"""engagement_engine

Revision ID: 34102091d180
Revises: 4fac28137c38
Create Date: 2026-02-26 17:30:48.007819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34102091d180'
down_revision: Union[str, Sequence[str], None] = '4fac28137c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins_diarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('nivel_humor', sa.Integer(), nullable=False),
    sa.Column('nivel_ansiedade', sa.Integer(), nullable=False),
    sa.Column('anotacao_paciente', sa.Text(), nullable=True),
    sa.CheckConstraint('nivel_ansiedade >= 1 AND nivel_ansiedade <= 10', name='ck_ansiedade_range'),
    sa.CheckConstraint('nivel_humor >= 1 AND nivel_humor <= 5', name='ck_humor_range'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkins_diarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkins_diarios_data_registro'), ['data_registro'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkins_diarios_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkins_diarios_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('notificacoes_lembretes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('lembrete_sessao', 'lembrete_tarefa', 'cobranca', name='tiponotificacao'), nullable=False),
    sa.Column('data_programada_disparo', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('agendada', 'enviada', 'falhou', name='statusnotificacao'), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificacoes_lembretes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacoes_lembretes_data_programada_disparo'), ['data_programada_disparo'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_lembretes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_lembretes_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('tarefas_paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_vencimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'concluida', 'nao_realizada', name='statustarefa'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarefas_paciente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarefas_paciente_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarefas_paciente_paciente_id'), ['paciente_id'], unique=False)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('pendente_aprovacao', 'ativo', 'inativo', 'alta', 'pausado', name='statuspaciente'),
               existing_nullable=False)

    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug_link_publico', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_psicologos_slug_link_publico'), ['slug_link_publico'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psicologos_slug_link_publico'))
        batch_op.drop_column('slug_link_publico')

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pendente_aprovacao', 'ativo', 'inativo', 'alta', 'pausado', name='statuspaciente'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    with op.batch_alter_table('tarefas_paciente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarefas_paciente_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_tarefas_paciente_id'))

    op.drop_table('tarefas_paciente')
    with op.batch_alter_table('notificacoes_lembretes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacoes_lembretes_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_lembretes_id'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_lembretes_data_programada_disparo'))

    op.drop_table('notificacoes_lembretes')
    with op.batch_alter_table('checkins_diarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkins_diarios_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_checkins_diarios_id'))
        batch_op.drop_index(batch_op.f('ix_checkins_diarios_data_registro'))

    op.drop_table('checkins_diarios')
    # ### end Alembic commands ###
