"""sessoes_faturas_anotacoes

Revision ID: 4fac28137c38
Revises: 2afd0b27af0a
Create Date: 2026-02-26 17:22:19.859672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fac28137c38'
down_revision: Union[str, Sequence[str], None] = '2afd0b27af0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.Integer(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('pendente', 'paga', 'atrasada', 'cancelada', name='estadofatura'), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faturas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faturas_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('sessoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Enum('agendada', 'realizada', 'falta_cobrada', 'cancelada_paciente', 'remarcada', name='estadosessao'), nullable=False),
    sa.Column('valor_cobrado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fatura_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fatura_id'], ['faturas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessoes_fatura_id'), ['fatura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessoes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessoes_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('anotacoes_clinicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('sessao_id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('evolucao_oficial', 'notas_pessoais', name='tipoanotacao'), nullable=False),
    sa.Column('data_registo', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anotacoes_clinicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anotacoes_clinicas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anotacoes_clinicas_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anotacoes_clinicas_sessao_id'), ['sessao_id'], unique=True)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               server_default=sa.text("'ativo'"),
               existing_nullable=False)

    with op.batch_alter_table('anotacoes_clinicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anotacoes_clinicas_sessao_id'))
        batch_op.drop_index(batch_op.f('ix_anotacoes_clinicas_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_anotacoes_clinicas_id'))

    op.drop_table('anotacoes_clinicas')
    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessoes_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_sessoes_id'))
        batch_op.drop_index(batch_op.f('ix_sessoes_fatura_id'))

    op.drop_table('sessoes')
    with op.batch_alter_table('faturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faturas_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_faturas_id'))

    op.drop_table('faturas')
    # ### end Alembic commands ###
