"""push_tokens_confirmada

Revision ID: 5b6fca99392a
Revises: 34102091d180
Create Date: 2026-02-26 17:38:26.708969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6fca99392a'
down_revision: Union[str, Sequence[str], None] = '34102091d180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispositivo_push_token', sa.String(length=256), nullable=True))

    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispositivo_push_token', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psicologos', schema=None) as batch_op:
        batch_op.drop_column('dispositivo_push_token')

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('dispositivo_push_token')

    # ### end Alembic commands ###
